### ISSUE TITLE
TunnelRelay Console V2 Alpha Crash On Windows

### ISSUE THREAD

**Issue by AlmogCohen** [OfficeDev/microsoft-teams-tunnelrelay#16]
Hi there!

Thanks for the awesome product :) I'm trying to get the TunnelRelay Console V2 working on windows. After I login and choose the region, the command line crash with exception

```
Unhandled Exception: System.AggregateException: One or more errors occurred. ---> Microsoft.Azure.Management.Relay.Fluent.Models.ErrorResponseException: Operation returned an invalid status code 'Conflict'
   at Microsoft.Azure.Management.Relay.Fluent.NamespacesOperations.<BeginCreateOrUpdateWithHttpMessagesAsync>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Management.Relay.Fluent.NamespacesOperations.<CreateOrUpdateWithHttpMessagesAsync>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Management.Relay.Fluent.NamespacesOperationsExtensions.<CreateOrUpdateAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at TunnelRelay.UI.ResourceManagement.ServiceBusResourceManager.<CreateHybridConnectionAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at TunnelRelay.Console.Program.<PerformInteractiveConfigurationAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at TunnelRelay.Console.Program.<>c__DisplayClass2_0.<<Main>b__0>d.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at Microsoft.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
   at TunnelRelay.Console.Program.Main(String[] args)
```

What do you think? Can you help? Thanks!

**Comment by AlmogCohen** [comment]
When I tried to run the `.msi` file and use the GUI, it crashed too when clicking the creation button. It said "Failed create Service Bus namespace" with no explanation. We would be very happy to use it!

**Comment by RamjotSingh** [comment]
From the error it seems that the creation of Relay on azure is failing. Can you try going to Azure portal and try creating an Azure Relay from there and then select the same in UI?

**Comment by AlmogCohen** [comment]
We'll check that and let you know soon...Thanks!
