### ISSUE TITLE
Create a new Azure Relay fails

### ISSUE THREAD

**Issue by machouMicrosoft** [OfficeDev/microsoft-teams-tunnelrelay#20]
When Creating a new Relay on Azure, the creation fails, probably because there is no way to select a Resource Group for Azure Relay in the UI.
![image](https://user-images.githubusercontent.com/38055502/81004477-4e6b7c80-8e01-11ea-85cf-c7e0cddcd9e1.png)

**Comment by derekmi** [comment]
I am receiving this same error when attempting to create a new relay using my Microsoft FTE credentials as of June 30th 2020:

<img width="516" alt="gui-version-error" src="https://user-images.githubusercontent.com/57726301/86174125-f46ff600-bad5-11ea-9859-632b755d1324.png">

I also receive an error when using the Windows Console standalone:

<img width="683" alt="console-version-error-crash" src="https://user-images.githubusercontent.com/57726301/86174174-081b5c80-bad6-11ea-9d62-7582e8053b46.png">

Stack trace:

```
Unhandled exception. System.AggregateException: One or more errors occurred. (Operation returned an invalid status code 'Conflict')
 ---> Microsoft.Azure.Management.Relay.Fluent.Models.ErrorResponseException: Operation returned an invalid status code 'Conflict'
   at Microsoft.Azure.Management.Relay.Fluent.NamespacesOperations.BeginCreateOrUpdateWithHttpMessagesAsync(String resourceGroupName, String namespaceName, RelayNamespaceInner parameters, Dictionary`2 customHeaders, CancellationToken cancellationToken)
   at Microsoft.Azure.Management.Relay.Fluent.NamespacesOperations.CreateOrUpdateWithHttpMessagesAsync(String resourceGroupName, String namespaceName, RelayNamespaceInner parameters, Dictionary`2 customHeaders, CancellationToken cancellationToken)
   at Microsoft.Azure.Management.Relay.Fluent.NamespacesOperationsExtensions.CreateOrUpdateAsync(INamespacesOperations operations, String resourceGroupName, String namespaceName, RelayNamespaceInner parameters, CancellationToken cancellationToken)
   at TunnelRelay.UI.ResourceManagement.AzureRelayResourceManager.CreateHybridConnectionAsync(SubscriptionInner subscription, String relayName, String hybridConnectionName, String locationName)
   at TunnelRelay.Console.Program.PerformInteractiveConfigurationAsync(IServiceProvider serviceProvider, String redirectionUrl)
   at TunnelRelay.Console.Program.<>c__DisplayClass1_0.<<Main>b__0>d.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at Microsoft.Extensions.CommandLineUtils.CommandLineApplication.<>c__DisplayClass79_0.<OnExecute>b__0()
   at Microsoft.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
   at TunnelRelay.Console.Program.Main(String[] args)
```

@RamjotSingh Please let me know if there are plans to investigate/resolve this issue.

**Comment by RamjotSingh** [comment]
From the error it looks like you are trying to create a new relay with the same name as one that exists. Can you check if this is the case (maybe from Azure portal)?

**Comment by derekmi** [comment]
I've since switched off a Windows machine to a Mac machine and cannot further debug the issue on Windows. I suggest closing this issue.

**Comment by ahmadgh7** [comment]
I'm still facing the same issue

![image](https://user-images.githubusercontent.com/24507502/89386625-fdbe3500-d709-11ea-9d27-72fb6d6c1cd3.png)

**Comment by RamjotSingh** [comment]
@ahmadgh7 Do you have permissions to create new relay on the said account (for example can you create it from Azure Portal)? Also can you share logs?

**Comment by ahmadgh7** [comment]
@RamjotSingh yes, this is my Microsoft FTE subscription and I already created one two years ago using v1 of Tunnel Relay. Now I need another one for a different purpose.
Where can I find the logs?

**Comment by RamjotSingh** [comment]
Oh conflict means that you already have a service bus with same name (I will work on making the errors more obvious). v1 and v2 run on different underlying Azure resource in a way (Azure has split one service into two dedicated to 2 use cases). If you want to keep same url, please delete the old relay and then create a new one, either through Azure Portal or Tunnel Relay.

[FAQ](https://github.com/OfficeDev/microsoft-teams-tunnelrelay#faqs) section in readme answer the question regarding v1 vs v2 resource change.

**Comment by ahmadgh7** [comment]
@RamjotSingh actually I don't. Unless it's trying to create the resource group again with the same name then there should be no conflict. I'm using a different name for the new service bus.

**Comment by RamjotSingh** [comment]
Can you try creating the hybrid connection from Azure Portal? Looks like Azure thinks their is a conflict. Remember the names have to be globally unique since it is a top level url.

**Comment by ahmadgh7** [comment]
@RamjotSingh creating the service bus from the Azure Portal was successful. But it's not appearing in the Tunnel Relay app.

**Comment by RamjotSingh** [comment]
Can you have a meeting with me?

**Comment by swasun99** [comment]
Hi @RamjotSingh/ @ahmadgh7 - Am facing the same issue currently, can you please let me know if this issue has been resolved?
