### ISSUE TITLE
Error when run on WSL

### ISSUE THREAD

**Issue by jongio** [OfficeDev/microsoft-teams-tunnelrelay#34]
I downloaded to WSL, ran this:
`./TunnelRelay.Linux.Console -RelayUrl jongrelay.servicebus.windows.net -KeyName RootManageSharedAccessKey -Key -Name jonghybrid -Address http://localhost:10000`

Got this:
```
Unhandled exception. System.AggregateException: One or more errors occurred. (Windows Data Protection API (DPAPI) is not supported on this platform.)
 ---> System.PlatformNotSupportedException: Windows Data Protection API (DPAPI) is not supported on this platform.
   at System.Security.Cryptography.ProtectedData.Protect(Byte[] userData, Byte[] optionalEntropy, DataProtectionScope scope)
   at TunnelRelay.UI.StateManagement.DataProtection.Protect(Byte[] data)
   at TunnelRelay.UI.StateManagement.ApplicationData.set_HybridConnectionSharedKey(String value)
   at TunnelRelay.Console.Program.<>c__DisplayClass1_0.<<Main>b__0>d.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at Microsoft.Extensions.CommandLineUtils.CommandLineApplication.<>c__DisplayClass79_0.<OnExecute>b__0()
   at Microsoft.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
   at TunnelRelay.Console.Program.Main(String[] args)
```

Should it be trying to use DPAPI on Linux?

azsdke2e
azsdke2e2

**Comment by RamjotSingh** [comment]
Yeah it should not be invoking DPAPI on Linux. Looks like a bug. I will take a look.

**Comment by RamjotSingh** [comment]
Looks like WSL is getting detected as Windows. Are you using WSL1 or WSL2?

**Comment by jongio** [comment]
2, thanks!

**Comment by RamjotSingh** [comment]
Looks like the older version of NetCore31 (on which tool is compiled) did not recognize WSL as Linux and hence you are hitting codepaths meant for Windows. I am adding a new flag for disabling encryption as well as increasing the netcore version to fix the existing issue.
