### ISSUE TITLE
"FAILED TO START AZURE PROXY!!!!" error message

### ISSUE THREAD

**Issue by v-kydela** [OfficeDev/microsoft-teams-tunnelrelay#36]
When I start Tunnel Relay in a remote desktop, the message "FAILED TO START AZURE PROXY!!!!" is displayed in the first input field:

![error](https://user-images.githubusercontent.com/41968495/127074170-9c7a16b2-41f7-4ef4-85a3-a78fb5d7bffc.png)

No debug information is given. What can I do to diagnose this problem?

**Comment by RamjotSingh** [comment]
Logs are dropped in temp folder (access using %Temp% in Windows Explorer) and start with name `TunnelRelay` followed by date and time of application start.

**Comment by v-kydela** [comment]
@RamjotSingh - Thanks, here's a log:

```
Information - string - Loading existing settings
Information - TunnelRelay.Windows.Startup - User is logged in already. Starting app directly
Error - TunnelRelay.Windows.MainWindow - Failed to establish connection to Azure RelayException - Microsoft.Azure.Relay.AuthorizationFailedException: Generic: Ip has been prevented to connect to the endpoint.\n           For more information see:\n           Virtual Network service endpoints:\n              Event Hubs: https://go.microsoft.com/fwlink/?linkid=2044192\n              Service Bus: https://go.microsoft.com/fwlink/?linkid=2044235\n           IP Filters:\n              Event Hubs:  https://go.microsoft.com/fwlink/?linkid=2044428\n              Service Bus: https://go.microsoft.com/fwlink/?linkid=2044183\n     TrackingId:2c516b56-fb6a-45da-a8aa-64d15834f5b0_G23, SystemTracker:sb://***.servicebus.windows.net/***, Timestamp:2021-07-26T23:46:19
 ---> System.Net.WebSockets.WebSocketException (997): The server returned status code '401' when status code '101' was expected.
   at Microsoft.Azure.Relay.WebSockets.NetCore21.WebSocketHandle.ConnectAsyncCore(Uri uri, CancellationToken cancellationToken, ClientWebSocketOptions options)
   at Microsoft.Azure.Relay.WebSockets.NetCore21.ClientWebSocket.ConnectAsyncCore(Uri uri, CancellationToken cancellationToken)
   at Microsoft.Azure.Relay.HybridConnectionListener.ControlConnection.ConnectAsync(CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at Microsoft.Azure.Relay.HybridConnectionListener.ControlConnection.ConnectAsync(CancellationToken cancellationToken)
   at Microsoft.Azure.Relay.HybridConnectionListener.ControlConnection.CloseOrAbortWebSocketAsync(Task`1 connectTask, Boolean abort, WebSocketCloseStatus closeStatus, String statusDescription, CancellationToken cancellationToken)
   at Microsoft.Azure.Relay.HybridConnectionListener.ControlConnection.OpenAsync(CancellationToken cancellationToken)
   at Microsoft.Azure.Relay.HybridConnectionListener.OpenAsync(CancellationToken cancellationToken)
   at TunnelRelay.Core.HybridConnectionManager.InitializeAsync(CancellationToken cancellationToken)
   at TunnelRelay.Windows.Engine.TunnelRelayStateManager.StartTunnelRelayAsync()
   at TunnelRelay.Windows.MainWindow.<StartRelayEngine>b__7_0()
```

I'm not quite sure what to make of that. What could be causing the 401? I know I successfully signed into my Azure account because it found the right relay resource. Could the problem be caused by using a remote desktop? Does this message imply that there's something wrong with the IP address? "Ip has been prevented to connect to the endpoint."

When I look at the hybrid connection that Tunnel Relay created in my relay resource, I notice that there's no shared access policy. Could that be the problem, or is Tunnel Relay able to connect to the hybrid connection without a shared access policy?

**Comment by RamjotSingh** [comment]
Hybrid connection can have 0 policies till the policy exists on the main account. I would recommend deleting the appSettings.json and trying to login again.

**Comment by v-kydela** [comment]
It worked! Thanks
