### ISSUE TITLE
Throwing "Failed to get list of subscriptions!! Existing"

### ISSUE THREAD

**Issue by yifanwu-microsoft** [OfficeDev/microsoft-teams-tunnelrelay#44]
Hi, I am developer who is using relay. It works fine yesterday. 
But it throw this issue today.
![image](https://user-images.githubusercontent.com/122973108/217420490-eb8347e9-6c73-44dc-9a0a-3fdc5fffdc31.png)

I have some fiddle logs here:
![image](https://user-images.githubusercontent.com/122973108/217420718-ab183b7d-f8b3-41c8-82ab-59e08ab9a43e.png)

**Comment by RamjotSingh** [comment]
Can you share logs from %Temp%. Logs start with TunnelRelay followed by date and time

**Comment by yifanwu-microsoft** [comment]
Information - string - Appsettings don't exist. Creating new one.
Information - TunnelRelay.Windows.Startup - Starting welcome experiance
Information - TunnelRelay.Windows.LoginToAzure - Starting Azure login.
Information - TunnelRelay.UI.ResourceManagement.UserAuthenticator - Logging the user in with Common tenant info
Information - TunnelRelay.UI.ResourceManagement.UserAuthenticator - Acquiring token with correlation Id set to '5e61843f-ebd4-4967-9af3-0c96b48d78ea'
Information - TunnelRelay.Windows.LoginToAzure - Token acquire complete.
Error - TunnelRelay.Windows.SelectAzureRelay - Failed to get user subscriptionsException - System.Threading.Tasks.TaskCanceledException: The operation was canceled.
 ---> System.IO.IOException: Unable to read data from the transport connection: The I/O operation has been aborted because of either a thread exit or an application request..
 ---> System.Net.Sockets.SocketException (995): The I/O operation has been aborted because of either a thread exit or an application request.
   --- End of inner exception stack trace ---
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.GetResult(Int16 token)
   at System.Net.Http.HttpConnection.ReadAsync(Memory`1 destination)
   at System.Net.Http.HttpConnection.RawConnectionStream.ReadAsync(Memory`1 buffer, CancellationToken cancellationToken)
   at System.Net.Security.SslStream.<FillBufferAsync>g__InternalFillBufferAsync|215_0[TReadAdapter](TReadAdapter adap, ValueTask`1 task, Int32 min, Int32 initial)
   at System.Net.Security.SslStream.ReadAsyncInternal[TReadAdapter](TReadAdapter adapter, Memory`1 buffer)
   at System.Net.Http.HttpConnection.FillAsync()
   at System.Net.Http.HttpConnection.ReadNextResponseHeaderLineAsync(Boolean foldedHeadersAllowed)
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithNtConnectionAuthAsync(HttpConnection connection, HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.Rest.RetryDelegatingHandler.<>c__DisplayClass11_0.<<SendAsync>b__1>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Rest.RetryDelegatingHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Microsoft.Azure.Management.ResourceManager.Fluent.TenantsOperations.ListWithHttpMessagesAsync(Dictionary`2 customHeaders, CancellationToken cancellationToken)
   at Microsoft.Azure.Management.ResourceManager.Fluent.TenantsOperationsExtensions.ListAsync(ITenantsOperations operations, CancellationToken cancellationToken)
   at TunnelRelay.UI.ResourceManagement.UserAuthenticator.GetUserSubscriptionsAsync()
   at TunnelRelay.Windows.SelectAzureRelay.<Window_ContentRendered>b__7_0()

**Comment by yifanwu-microsoft** [comment]
This also happens to my colleague, we are in the same company network

**Comment by yifanwu-microsoft** [comment]
It works now. It seems upstream api failure issue. 
Thanks!
